version: 2
jobs:
  compile:
    working_directory: ~/docker-cadvisor
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: make BUILD_BASE=base
  build_amd64:
    working_directory: ~/docker-cadvisor
    machine: true
    steps:
      - checkout
      - run: make BUILD_BASE=base ARCHITECTURES=amd64
      - run: make BUILD_BASE=base ARCHITECTURES=amd64 push
  build_i386:
    working_directory: ~/docker-cadvisor
    machine: true
    steps:
      - checkout
      - run: make BUILD_BASE=base ARCHITECTURES=i386
      - run: make BUILD_BASE=base ARCHITECTURES=i386 push
  build_arm32v7:
    working_directory: ~/docker-cadvisor
    machine: true
    steps:
      - checkout
      - run: make BUILD_BASE=base ARCHITECTURES=arm32v7
      - run: make BUILD_BASE=base ARCHITECTURES=arm32v7 push
  build_arm64v8:
    working_directory: ~/docker-cadvisor
    machine: true
    steps:
      - checkout
      - run: make BUILD_BASE=base ARCHITECTURES=arm64v8
      - run: make BUILD_BASE=base ARCHITECTURES=arm64v8 push
  manifest:
    machine: true
    steps:
      - checkout
      - run: make manifest
  badge:
    machine: true
    steps:
      - run: curl -X POST https://hooks.microbadger.com/images/unibaktr/cadvisor/Fip_9kcTN5C9Fp0aDrXhhOlpX0Y=

workflows:
  version: 2
  build-and-deploy:
      - build_compile:
        filters:
          tags:
            only: /.*/
      - build_amd64:
          requires:
            - build_compile
          filters:
            tags:
              only: /.*/
      - build_i386:
          requires:
            - build_compile
          filters:
            tags:
              only: /.*/
      - build_arm32v7:
          requires:
            - build_compile
          filters:
            tags:
              only: /.*/
      - build_arm64v8:
          requires:
            - build_compile
          filters:
            tags:
              only: /.*/
      - manifest:
          requires:
            - build_amd64
            - build_i386
            - build_arm32v7
            - build_arm64v8
          filters:
            tags:
              only: /.*/
      - badge:
          requires:
            - manifest
          filters:
            tags:
              only: /.*/
