version: 2
defaults: &defaults
  working_directory: ~/docker-cadvisor
  machine: true

save_docker_cache: &save_docker_cache
  save_cache:
    key: compiled
    paths: docker-cache

restore_docker_cache: &restore_docker_cache
  restore_cache:
    key: compiled

load_image_from_cache: &load_image_from_cache
  run:
    name: Load docker image from cache
    command:
      docker load < docker-cache/base.tar

workflow_filter: &workflow_filter
  filters:
    tags:
      only: /.*/

jobs:
  compile_go:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Do the compile steps
          command: |
            make BUILD_BASE=base base
            mkdir -p docker-cache
            docker save -o docker-cache/base.tar base
      - *save_docker_cache
  build_amd64:
    <<: *defaults
    steps:
      - checkout
      - *restore_docker_cache
      - *load_image_from_cache
      - run:
          name: Build image
          command: |
            make BUILD_BASE=base ARCHITECTURES=amd64
      - run:
          name: Push image to dockerhub
          command: |
            make BUILD_BASE=base ARCHITECTURES=amd64 push
  build_i386:
    <<: *defaults
    steps:
      - checkout
      - *restore_docker_cache
      - *load_image_from_cache
      - run: make BUILD_BASE=base ARCHITECTURES=i386
      - run: make BUILD_BASE=base ARCHITECTURES=i386 push
  build_arm32v7:
    <<: *defaults
    steps:
      - checkout
      - *restore_docker_cache
      - *load_image_from_cache
      - run: make BUILD_BASE=base ARCHITECTURES=arm32v7
      - run: make BUILD_BASE=base ARCHITECTURES=arm32v7 push
  build_arm64v8:
      <<: *defaults
      steps:
        - checkout
        - *restore_docker_cache
        - *load_image_from_cache
      - run: make BUILD_BASE=base ARCHITECTURES=arm64v8
      - run: make BUILD_BASE=base ARCHITECTURES=arm64v8 push
  manifest:
    <<: *defaults
    steps:
      - checkout
      - run: make manifest
  badge:
    <<: *defaults
    steps:
      - run: curl -X POST https://hooks.microbadger.com/images/unibaktr/cadvisor/Fip_9kcTN5C9Fp0aDrXhhOlpX0Y=

workflows:
  version: 2
  compile-build-and-deploy:
    jobs:
      - compile_go:
          *workflow_filter
      - build_amd64:
          requires:
            - compile_go
          *workflow_filter
      - build_i386:
          requires:
            - compile_go
          *workflow_filter
      - build_arm32v7:
          requires:
            - compile_go
          *workflow_filter
      - build_arm64v8:
          requires:
            - compile_go
          *workflow_filter
      - manifest:
          requires:
            - build_amd64
            - build_i386
            - build_arm32v7
            - build_arm64v8
          *workflow_filter
      - badge:
          requires:
            - manifest
          *workflow_filter
